language: node_js

node_js:
  - lts/*

cache: yarn

before_script:
  - sed  "s!{HOOK_URL}!${HOOK_URL}!" index.js > _index.js
  - mv _index.js index.js

script: 
  - node index.js javascript
  - node index.js python

